# Generated by Django 4.2.7 on 2023-11-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_farmer_alter_agricultural_product_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultural_product',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
