# Generated by Django 4.2.6 on 2023-10-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agricultural_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='products')),
            ],
            options={
                'db_table': 'agricultural_product',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('wallet', models.CharField(max_length=50)),
                ('Birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('id_agricultural_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_app.agricultural_product')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='harvester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='harvesters')),
                ('ubication', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('id_agricultural_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_app.agricultural_product')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='calification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calification', models.IntegerField()),
                ('comment', models.CharField(max_length=50)),
                ('id_agricultural_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_app.agricultural_product')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro_app.user')),
            ],
        ),
    ]
