# Generated by Django 4.2.6 on 2023-10-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_app', '0002_alter_agricultural_product_id_alter_calification_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agricultural_product',
            name='description',
        ),
    ]
