# Generated by Django 4.2.6 on 2023-10-17 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_app', '0003_remove_agricultural_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calification',
            name='comment',
        ),
        migrations.AddField(
            model_name='agricultural_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
