# Generated by Django 4.2.6 on 2023-10-17 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_app', '0004_remove_calification_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultural_product',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calification',
            name='comment',
            field=models.TextField(default=57),
            preserve_default=False,
        ),
    ]
