# Generated by Django 4.2.6 on 2023-10-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_app', '0007_alter_agricultural_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultural_product',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
